apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::637423534542:role/eks-worker-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::637423534542:role/eks-cluster-role
      username: cluster-admin
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::637423534542:user/kubernetes
      username: kubernetes-user
      groups:
        - system:masters
